import './client.spec'
import './exports.spec'

import './integration/client/graphql.spec'
import './integration/client/products.spec'
import './integration/auth.spec'
import './integration/task-queue.spec'

import './services/graphql.spec'
import './services/product-projections.spec'

import './utils/auth.spec'
import './utils/build-absolute-url.spec'
import './utils/build-query-string.spec'
import './utils/classify.spec'
import './utils/create-service.spec'
import './utils/default-params.spec'
import './utils/diffpatcher.spec'
import './utils/errors.spec'
import './utils/handle-response.spec'
import './utils/http.spec'
import './utils/query-custom.spec'
import './utils/query-expand.spec'
import './utils/query-id.spec'
import './utils/query-page.spec'
import './utils/query-projection.spec'
import './utils/query-search.spec'
import './utils/query.spec'
import './utils/task-queue.spec'
import './utils/verbs.spec'
import './utils/with-helpers.spec'


import './sync/category-sync.spec'
import './sync/customer-sync.spec'
import './sync/inventory-sync.spec'
import './sync/product-sync-base.spec'
import './sync/product-sync-images.spec'
import './sync/product-sync-prices.spec'
import './sync/product-sync-variants.spec'
import './sync/utils/common-actions.spec'
import './sync/utils/create-build-array-actions.spec'
