export const read = 'read'
export const create = 'create'
export const update = 'update'
const _delete = 'delete'
export { _delete as delete }
export const query = 'query'
export const queryOne = 'queryOne'
export const queryExpand = 'queryExpand'
export const queryString = 'queryString'
export const search = 'search'
export const projection = 'projection'
