/* eslint-disable max-len */

// Feature types
export const FEATURE_READ = 'FEATURE_READ'
export const FEATURE_CREATE = 'FEATURE_CREATE'
export const FEATURE_UPDATE = 'FEATURE_UPDATE'
export const FEATURE_DELETE = 'FEATURE_DELETE'
export const FEATURE_QUERY = 'FEATURE_QUERY'
export const FEATURE_QUERY_ONE = 'FEATURE_QUERY_ONE'
export const FEATURE_QUERY_EXPAND = 'FEATURE_QUERY_EXPAND'
export const FEATURE_QUERY_STRING = 'FEATURE_QUERY_STRING'
export const FEATURE_SEARCH = 'FEATURE_SEARCH'
export const FEATURE_PROJECTION = 'FEATURE_PROJECTION'

// Task types
export const TASK = 'TASK'
export const TASK_SUCCESS = 'TASK_SUCCESS'
export const TASK_ERROR = 'TASK_ERROR'

// Http verbs
export const HTTP_FETCH = 'HTTP_FETCH'
export const HTTP_CREATE = 'HTTP_CREATE'
export const HTTP_UPDATE = 'HTTP_UPDATE'
export const HTTP_DELETE = 'HTTP_DELETE'
export const HTTP_GRAPHQL_QUERY = 'HTTP_GRAPHQL_QUERY'

// Request actions
export const REQUEST_TOKEN = 'REQUEST_TOKEN'
export const REQUEST_PROJECT_KEY = 'REQUEST_PROJECT_KEY'

// Service actions
export const SERVICE_INIT = 'SERVICE_INIT'
export const SERVICE_PARAMS_RESET = 'SERVICE_PARAMS_RESET'

export const SERVICE_PARAM_ID = 'SERVICE_PARAM_ID'

export const SERVICE_PARAM_QUERY_STAGED = 'SERVICE_PARAM_QUERY_STAGED'
export const SERVICE_PARAM_QUERY_EXPAND = 'SERVICE_PARAM_QUERY_EXPAND'
export const SERVICE_PARAM_QUERY_PAGE = 'SERVICE_PARAM_QUERY_PAGE'
export const SERVICE_PARAM_QUERY_PER_PAGE = 'SERVICE_PARAM_QUERY_PER_PAGE'
export const SERVICE_PARAM_QUERY_SORT = 'SERVICE_PARAM_QUERY_SORT'
export const SERVICE_PARAM_QUERY_WHERE = 'SERVICE_PARAM_QUERY_WHERE'
export const SERVICE_PARAM_QUERY_WHERE_OPERATOR = 'SERVICE_PARAM_QUERY_WHERE_OPERATOR'

export const SERVICE_PARAM_QUERY_SEARCH_FACET = 'SERVICE_PARAM_QUERY_SEARCH_FACET'
export const SERVICE_PARAM_QUERY_SEARCH_FILTER = 'SERVICE_PARAM_QUERY_SEARCH_FILTER'
export const SERVICE_PARAM_QUERY_SEARCH_FILTER_BY_QUERY = 'SERVICE_PARAM_QUERY_SEARCH_FILTER_BY_QUERY'
export const SERVICE_PARAM_QUERY_SEARCH_FILTER_BY_FACETS = 'SERVICE_PARAM_QUERY_SEARCH_FILTER_BY_FACETS'
export const SERVICE_PARAM_QUERY_SEARCH_FUZZY = 'SERVICE_PARAM_QUERY_SEARCH_FUZZY'
export const SERVICE_PARAM_QUERY_SEARCH_TEXT = 'SERVICE_PARAM_QUERY_SEARCH_TEXT'

export const SERVICE_PARAM_QUERY_CUSTOM = 'SERVICE_PARAM_QUERY_CUSTOM'
